num1, num2 = input().split()
num1 = int(num1)
num2 = int(num2)
print(eval("num1+num2"), eval("num1-num2"), eval("num1*num2"), int(eval("num1/num2")), eval("num1%num2"))
# print(eval("num1-num2"))
# print(eval("num1*num2"))
# print(eval("num1/num2"))
# print(eval("num1%num2"))
