# Generated by Django 4.0.4 on 2022-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mail', models.CharField(max_length=100)),
                ('reg_pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
