from tkinter import *

root = Tk()
root.geometry("200x200+280+280")
root.title("计算器")
B1 = Button(root, text="1", width=5, fg="yellow")
B2 = Button(root,text="2",width=5)
B3 = Button(root,text="3",width=5)
B4 = Button(root,text="4",width=5)
B5 = Button(root,text="5",width=5,fg="green")
B6 = Button(root,text="6",width=5)
B7 = Button(root,text="7",width=5)
B8 = Button(root,text="8",width=5)
B9 = Button(root,text="9",width=5,fg="yellow")
B0 = Button(root,text="0")
BP = Button(root,text=".",width=5)

B1.grid(row=0, column=0)
B2.grid(row=0,column=1)
B3.grid(row=0,column=2)
B4.grid(row=1,column=0)
B5.grid(row=1,column=1)
B6.grid(row=1,column=2)
B7.grid(row=2,column=0)
B8.grid(row=2,column=1)
B9.grid(row=2,column=2)
B0.grid(row=3,column=0,columnspan=2,sticky=E+W)
BP.grid(row=3,column=2)
root.mainloop()
